; AUTO-GENERATED by tools/shader_bundle.ps1 -- DO NOT EDIT
; Regenerate: powershell -File tools/shader_bundle.ps1
#Requires AutoHotkey v2.0
#Warn VarUnset, Off

; Texture resources (IDs 100+)
;@Ahk2Exe-AddResource ..\resources\img\shaders\abstract_glassy_field_i0.png, 100
;@Ahk2Exe-AddResource ..\resources\img\shaders\abstract_glassy_field_i1.jpg, 101
;@Ahk2Exe-AddResource ..\resources\img\shaders\alien_spawning_pool_i0.png, 102
;@Ahk2Exe-AddResource ..\resources\img\shaders\black_hole_accretion_disk_i0.jpg, 103
;@Ahk2Exe-AddResource ..\resources\img\shaders\bmtest2_i0.png, 104
;@Ahk2Exe-AddResource ..\resources\img\shaders\digital_brain_i0.png, 105
;@Ahk2Exe-AddResource ..\resources\img\shaders\digital_rain_i0.png, 106
;@Ahk2Exe-AddResource ..\resources\img\shaders\digital_rain_i1.png, 107
;@Ahk2Exe-AddResource ..\resources\img\shaders\domain_warped_fbm_noise_i0.png, 108
;@Ahk2Exe-AddResource ..\resources\img\shaders\enter_the_matrix_i0.png, 109
;@Ahk2Exe-AddResource ..\resources\img\shaders\gargantua_render_i0.png, 110
;@Ahk2Exe-AddResource ..\resources\img\shaders\gargantua_render_i1.jpg, 111
;@Ahk2Exe-AddResource ..\resources\img\shaders\holographic_liquid_i0.png, 112
;@Ahk2Exe-AddResource ..\resources\img\shaders\interstellar_i0.png, 113
;@Ahk2Exe-AddResource ..\resources\img\shaders\liquid_warp_i0.png, 114
;@Ahk2Exe-AddResource ..\resources\img\shaders\nebula_flight_i0.png, 115
;@Ahk2Exe-AddResource ..\resources\img\shaders\nebula_flight_i1.png, 116
;@Ahk2Exe-AddResource ..\resources\img\shaders\neon_plasma_storm_i0.png, 117
;@Ahk2Exe-AddResource ..\resources\img\shaders\neon_plasma_storm_i1.png, 118
;@Ahk2Exe-AddResource ..\resources\img\shaders\noise_animation_electric_i0.png, 119
;@Ahk2Exe-AddResource ..\resources\img\shaders\noise_animation_flow_i0.png, 120
;@Ahk2Exe-AddResource ..\resources\img\shaders\oily_thing_i0.png, 121
;@Ahk2Exe-AddResource ..\resources\img\shaders\overstimulated_neurons_i0.png, 122
;@Ahk2Exe-AddResource ..\resources\img\shaders\starship_i0.png, 123
;@Ahk2Exe-AddResource ..\resources\img\shaders\sun_surface_i0.png, 124
;@Ahk2Exe-AddResource ..\resources\img\shaders\toxic_lake_i0.png, 125
;@Ahk2Exe-AddResource ..\resources\img\shaders\voronoi_burning_i0.png, 126

; DXBC bytecode resources (IDs 1000+)
;@Ahk2Exe-AddResource ..\resources\shaders\vs_VSMain.bin, 1000
;@Ahk2Exe-AddResource ..\resources\shaders\ps_2dClouds.bin, 1001
;@Ahk2Exe-AddResource ..\resources\shaders\ps_4dLavaLamp.bin, 1002
;@Ahk2Exe-AddResource ..\resources\shaders\ps_70sMelt.bin, 1003
;@Ahk2Exe-AddResource ..\resources\shaders\ps_abstractGlassyField.bin, 1004
;@Ahk2Exe-AddResource ..\resources\shaders\ps_abstractPainting.bin, 1005
;@Ahk2Exe-AddResource ..\resources\shaders\ps_abstractShine.bin, 1006
;@Ahk2Exe-AddResource ..\resources\shaders\ps_abstractVortex.bin, 1007
;@Ahk2Exe-AddResource ..\resources\shaders\ps_accretion.bin, 1008
;@Ahk2Exe-AddResource ..\resources\shaders\ps_alienSkin.bin, 1009
;@Ahk2Exe-AddResource ..\resources\shaders\ps_alienSpawningPool.bin, 1010
;@Ahk2Exe-AddResource ..\resources\shaders\ps_anotherWindowsTerminalShader.bin, 1011
;@Ahk2Exe-AddResource ..\resources\shaders\ps_ascend.bin, 1012
;@Ahk2Exe-AddResource ..\resources\shaders\ps_balatroBackground.bin, 1013
;@Ahk2Exe-AddResource ..\resources\shaders\ps_balatroTwist.bin, 1014
;@Ahk2Exe-AddResource ..\resources\shaders\ps_baseWarpFbm.bin, 1015
;@Ahk2Exe-AddResource ..\resources\shaders\ps_bentHorizon.bin, 1016
;@Ahk2Exe-AddResource ..\resources\shaders\ps_blackHoleAccretionDisk.bin, 1017
;@Ahk2Exe-AddResource ..\resources\shaders\ps_bloodCells.bin, 1018
;@Ahk2Exe-AddResource ..\resources\shaders\ps_blueMoonOcean.bin, 1019
;@Ahk2Exe-AddResource ..\resources\shaders\ps_blurryCircles.bin, 1020
;@Ahk2Exe-AddResource ..\resources\shaders\ps_bmTesting04.bin, 1021
;@Ahk2Exe-AddResource ..\resources\shaders\ps_bmtest2.bin, 1022
;@Ahk2Exe-AddResource ..\resources\shaders\ps_bokehExpe03.bin, 1023
;@Ahk2Exe-AddResource ..\resources\shaders\ps_bokehGradient.bin, 1024
;@Ahk2Exe-AddResource ..\resources\shaders\ps_bokehLights.bin, 1025
;@Ahk2Exe-AddResource ..\resources\shaders\ps_bokehParallax.bin, 1026
;@Ahk2Exe-AddResource ..\resources\shaders\ps_brainfall.bin, 1027
;@Ahk2Exe-AddResource ..\resources\shaders\ps_cheapOcean.bin, 1028
;@Ahk2Exe-AddResource ..\resources\shaders\ps_chillSmokeOrb.bin, 1029
;@Ahk2Exe-AddResource ..\resources\shaders\ps_clearlyABug.bin, 1030
;@Ahk2Exe-AddResource ..\resources\shaders\ps_colorFadePattern.bin, 1031
;@Ahk2Exe-AddResource ..\resources\shaders\ps_colorfog.bin, 1032
;@Ahk2Exe-AddResource ..\resources\shaders\ps_colorfulFbmDomainWarping.bin, 1033
;@Ahk2Exe-AddResource ..\resources\shaders\ps_cosmicFbmNoise.bin, 1034
;@Ahk2Exe-AddResource ..\resources\shaders\ps_crumpledWave.bin, 1035
;@Ahk2Exe-AddResource ..\resources\shaders\ps_cubeWave3.bin, 1036
;@Ahk2Exe-AddResource ..\resources\shaders\ps_damaskRose.bin, 1037
;@Ahk2Exe-AddResource ..\resources\shaders\ps_deterioration.bin, 1038
;@Ahk2Exe-AddResource ..\resources\shaders\ps_digitalBrain.bin, 1039
;@Ahk2Exe-AddResource ..\resources\shaders\ps_digitalRain.bin, 1040
;@Ahk2Exe-AddResource ..\resources\shaders\ps_discoInferno.bin, 1041
;@Ahk2Exe-AddResource ..\resources\shaders\ps_domainWarpedFbmNoise.bin, 1042
;@Ahk2Exe-AddResource ..\resources\shaders\ps_domainWarpingLearn.bin, 1043
;@Ahk2Exe-AddResource ..\resources\shaders\ps_domainWarpingOil.bin, 1044
;@Ahk2Exe-AddResource ..\resources\shaders\ps_domainWarpingTest.bin, 1045
;@Ahk2Exe-AddResource ..\resources\shaders\ps_drawCircle.bin, 1046
;@Ahk2Exe-AddResource ..\resources\shaders\ps_driftingWaves.bin, 1047
;@Ahk2Exe-AddResource ..\resources\shaders\ps_duneSandworm.bin, 1048
;@Ahk2Exe-AddResource ..\resources\shaders\ps_enterTheMatrix.bin, 1049
;@Ahk2Exe-AddResource ..\resources\shaders\ps_exitTheMatrix.bin, 1050
;@Ahk2Exe-AddResource ..\resources\shaders\ps_explosiveTurbulentNoise.bin, 1051
;@Ahk2Exe-AddResource ..\resources\shaders\ps_fakingGoldAndMurder.bin, 1052
;@Ahk2Exe-AddResource ..\resources\shaders\ps_fateBeckons.bin, 1053
;@Ahk2Exe-AddResource ..\resources\shaders\ps_fbmDomainWarping.bin, 1054
;@Ahk2Exe-AddResource ..\resources\shaders\ps_fbmNoise.bin, 1055
;@Ahk2Exe-AddResource ..\resources\shaders\ps_fire.bin, 1056
;@Ahk2Exe-AddResource ..\resources\shaders\ps_fireAndWater.bin, 1057
;@Ahk2Exe-AddResource ..\resources\shaders\ps_flowerOfFractal.bin, 1058
;@Ahk2Exe-AddResource ..\resources\shaders\ps_forkTheDrive.bin, 1059
;@Ahk2Exe-AddResource ..\resources\shaders\ps_fractalGalaxyParallax.bin, 1060
;@Ahk2Exe-AddResource ..\resources\shaders\ps_galvanizeTunnel.bin, 1061
;@Ahk2Exe-AddResource ..\resources\shaders\ps_gargantuaRender.bin, 1062
;@Ahk2Exe-AddResource ..\resources\shaders\ps_glasswall.bin, 1063
;@Ahk2Exe-AddResource ..\resources\shaders\ps_glassyWithOddRotation.bin, 1064
;@Ahk2Exe-AddResource ..\resources\shaders\ps_glittery.bin, 1065
;@Ahk2Exe-AddResource ..\resources\shaders\ps_glowingMarblingBlack.bin, 1066
;@Ahk2Exe-AddResource ..\resources\shaders\ps_goldAgate.bin, 1067
;@Ahk2Exe-AddResource ..\resources\shaders\ps_greyLiquid.bin, 1068
;@Ahk2Exe-AddResource ..\resources\shaders\ps_happyLittleWindowsTerminal.bin, 1069
;@Ahk2Exe-AddResource ..\resources\shaders\ps_holographicLiquid.bin, 1070
;@Ahk2Exe-AddResource ..\resources\shaders\ps_horizonZeroDawnClouds2d.bin, 1071
;@Ahk2Exe-AddResource ..\resources\shaders\ps_inSpace.bin, 1072
;@Ahk2Exe-AddResource ..\resources\shaders\ps_insideTheMatrix.bin, 1073
;@Ahk2Exe-AddResource ..\resources\shaders\ps_interstellar.bin, 1074
;@Ahk2Exe-AddResource ..\resources\shaders\ps_isItStillRaymarching.bin, 1075
;@Ahk2Exe-AddResource ..\resources\shaders\ps_isoScreensaver.bin, 1076
;@Ahk2Exe-AddResource ..\resources\shaders\ps_iteratingCaustics.bin, 1077
;@Ahk2Exe-AddResource ..\resources\shaders\ps_jaszUniverse.bin, 1078
;@Ahk2Exe-AddResource ..\resources\shaders\ps_kaleidoscopeCrystal.bin, 1079
;@Ahk2Exe-AddResource ..\resources\shaders\ps_kaleidoscopeTunnel.bin, 1080
;@Ahk2Exe-AddResource ..\resources\shaders\ps_lazerBeamz.bin, 1081
;@Ahk2Exe-AddResource ..\resources\shaders\ps_limestoneCave.bin, 1082
;@Ahk2Exe-AddResource ..\resources\shaders\ps_lineSynapse.bin, 1083
;@Ahk2Exe-AddResource ..\resources\shaders\ps_liquidWarp.bin, 1084
;@Ahk2Exe-AddResource ..\resources\shaders\ps_metalVortex.bin, 1085
;@Ahk2Exe-AddResource ..\resources\shaders\ps_monster.bin, 1086
;@Ahk2Exe-AddResource ..\resources\shaders\ps_nanosecondsAfterBigbang.bin, 1087
;@Ahk2Exe-AddResource ..\resources\shaders\ps_nebulaFlight.bin, 1088
;@Ahk2Exe-AddResource ..\resources\shaders\ps_nebulaSmoke.bin, 1089
;@Ahk2Exe-AddResource ..\resources\shaders\ps_neonPlasmaStorm.bin, 1090
;@Ahk2Exe-AddResource ..\resources\shaders\ps_noiseAccident.bin, 1091
;@Ahk2Exe-AddResource ..\resources\shaders\ps_noiseAnimationElectric.bin, 1092
;@Ahk2Exe-AddResource ..\resources\shaders\ps_noiseAnimationFlow.bin, 1093
;@Ahk2Exe-AddResource ..\resources\shaders\ps_noiseCristal.bin, 1094
;@Ahk2Exe-AddResource ..\resources\shaders\ps_noiseOil.bin, 1095
;@Ahk2Exe-AddResource ..\resources\shaders\ps_nox.bin, 1096
;@Ahk2Exe-AddResource ..\resources\shaders\ps_oVortex.bin, 1097
;@Ahk2Exe-AddResource ..\resources\shaders\ps_oilyThing.bin, 1098
;@Ahk2Exe-AddResource ..\resources\shaders\ps_opticalSpaghetti.bin, 1099
;@Ahk2Exe-AddResource ..\resources\shaders\ps_organicTexture.bin, 1100
;@Ahk2Exe-AddResource ..\resources\shaders\ps_overstimulatedNeurons.bin, 1101
;@Ahk2Exe-AddResource ..\resources\shaders\ps_paint1.bin, 1102
;@Ahk2Exe-AddResource ..\resources\shaders\ps_paintArchipelago.bin, 1103
;@Ahk2Exe-AddResource ..\resources\shaders\ps_palaceOfMind.bin, 1104
;@Ahk2Exe-AddResource ..\resources\shaders\ps_pathToTheColorfulInfinity.bin, 1105
;@Ahk2Exe-AddResource ..\resources\shaders\ps_perhapsAScreensaver.bin, 1106
;@Ahk2Exe-AddResource ..\resources\shaders\ps_pinwheelTrianglesScreensaver.bin, 1107
;@Ahk2Exe-AddResource ..\resources\shaders\ps_playingWithFbm.bin, 1108
;@Ahk2Exe-AddResource ..\resources\shaders\ps_powerChainSawMan.bin, 1109
;@Ahk2Exe-AddResource ..\resources\shaders\ps_prettyColors.bin, 1110
;@Ahk2Exe-AddResource ..\resources\shaders\ps_prettyHip.bin, 1111
;@Ahk2Exe-AddResource ..\resources\shaders\ps_processingData.bin, 1112
;@Ahk2Exe-AddResource ..\resources\shaders\ps_proteanClouds.bin, 1113
;@Ahk2Exe-AddResource ..\resources\shaders\ps_rainbowScreensaverAnimation.bin, 1114
;@Ahk2Exe-AddResource ..\resources\shaders\ps_raindropsGlass.bin, 1115
;@Ahk2Exe-AddResource ..\resources\shaders\ps_raymarchingWaves.bin, 1116
;@Ahk2Exe-AddResource ..\resources\shaders\ps_reflectiveTruchet.bin, 1117
;@Ahk2Exe-AddResource ..\resources\shaders\ps_retroScreensaverLines.bin, 1118
;@Ahk2Exe-AddResource ..\resources\shaders\ps_rocaille.bin, 1119
;@Ahk2Exe-AddResource ..\resources\shaders\ps_rotatingTorus.bin, 1120
;@Ahk2Exe-AddResource ..\resources\shaders\ps_satinlike.bin, 1121
;@Ahk2Exe-AddResource ..\resources\shaders\ps_satori.bin, 1122
;@Ahk2Exe-AddResource ..\resources\shaders\ps_screensaverWarpedGradWaves.bin, 1123
;@Ahk2Exe-AddResource ..\resources\shaders\ps_seaAdventure.bin, 1124
;@Ahk2Exe-AddResource ..\resources\shaders\ps_shadetober29Injured.bin, 1125
;@Ahk2Exe-AddResource ..\resources\shaders\ps_simpleScreensaver.bin, 1126
;@Ahk2Exe-AddResource ..\resources\shaders\ps_simplex3dFbm.bin, 1127
;@Ahk2Exe-AddResource ..\resources\shaders\ps_singularity.bin, 1128
;@Ahk2Exe-AddResource ..\resources\shaders\ps_smokeFlythrough.bin, 1129
;@Ahk2Exe-AddResource ..\resources\shaders\ps_softWhisper.bin, 1130
;@Ahk2Exe-AddResource ..\resources\shaders\ps_spaceEye2.bin, 1131
;@Ahk2Exe-AddResource ..\resources\shaders\ps_sparksFromFire.bin, 1132
;@Ahk2Exe-AddResource ..\resources\shaders\ps_spiralsForWindowsTerminal.bin, 1133
;@Ahk2Exe-AddResource ..\resources\shaders\ps_starNew.bin, 1134
;@Ahk2Exe-AddResource ..\resources\shaders\ps_starShine.bin, 1135
;@Ahk2Exe-AddResource ..\resources\shaders\ps_starfieldSimV2.bin, 1136
;@Ahk2Exe-AddResource ..\resources\shaders\ps_starfieldWithFbm.bin, 1137
;@Ahk2Exe-AddResource ..\resources\shaders\ps_starleidoscope.bin, 1138
;@Ahk2Exe-AddResource ..\resources\shaders\ps_starship.bin, 1139
;@Ahk2Exe-AddResource ..\resources\shaders\ps_sunSurface.bin, 1140
;@Ahk2Exe-AddResource ..\resources\shaders\ps_tentaclesOfLight.bin, 1141
;@Ahk2Exe-AddResource ..\resources\shaders\ps_tileableWaterCaustic.bin, 1142
;@Ahk2Exe-AddResource ..\resources\shaders\ps_tilesInterestingPatterns.bin, 1143
;@Ahk2Exe-AddResource ..\resources\shaders\ps_toxicLake.bin, 1144
;@Ahk2Exe-AddResource ..\resources\shaders\ps_triangleNoise.bin, 1145
;@Ahk2Exe-AddResource ..\resources\shaders\ps_turbulenceTexture.bin, 1146
;@Ahk2Exe-AddResource ..\resources\shaders\ps_ultraLiquidBokeh.bin, 1147
;@Ahk2Exe-AddResource ..\resources\shaders\ps_underwaterCaustics.bin, 1148
;@Ahk2Exe-AddResource ..\resources\shaders\ps_vistaEsqueWallpaper.bin, 1149
;@Ahk2Exe-AddResource ..\resources\shaders\ps_volumetricFire.bin, 1150
;@Ahk2Exe-AddResource ..\resources\shaders\ps_voronoiBurning.bin, 1151
;@Ahk2Exe-AddResource ..\resources\shaders\ps_warpedLiquidMetal.bin, 1152
;@Ahk2Exe-AddResource ..\resources\shaders\ps_worleyNoiseWaters.bin, 1153
;@Ahk2Exe-AddResource ..\resources\shaders\ps_wormCity.bin, 1154

global RES_ID_SHADER_ABSTRACTGLASSYFIELD_I0 := 100
global RES_ID_SHADER_ABSTRACTGLASSYFIELD_I1 := 101
global RES_ID_SHADER_ALIENSPAWNINGPOOL_I0 := 102
global RES_ID_SHADER_BLACKHOLEACCRETIONDISK_I0 := 103
global RES_ID_SHADER_BMTEST2_I0 := 104
global RES_ID_SHADER_DIGITALBRAIN_I0 := 105
global RES_ID_SHADER_DIGITALRAIN_I0 := 106
global RES_ID_SHADER_DIGITALRAIN_I1 := 107
global RES_ID_SHADER_DOMAINWARPEDFBMNOISE_I0 := 108
global RES_ID_SHADER_ENTERTHEMATRIX_I0 := 109
global RES_ID_SHADER_GARGANTUARENDER_I0 := 110
global RES_ID_SHADER_GARGANTUARENDER_I1 := 111
global RES_ID_SHADER_HOLOGRAPHICLIQUID_I0 := 112
global RES_ID_SHADER_INTERSTELLAR_I0 := 113
global RES_ID_SHADER_LIQUIDWARP_I0 := 114
global RES_ID_SHADER_NEBULAFLIGHT_I0 := 115
global RES_ID_SHADER_NEBULAFLIGHT_I1 := 116
global RES_ID_SHADER_NEONPLASMASTORM_I0 := 117
global RES_ID_SHADER_NEONPLASMASTORM_I1 := 118
global RES_ID_SHADER_NOISEANIMATIONELECTRIC_I0 := 119
global RES_ID_SHADER_NOISEANIMATIONFLOW_I0 := 120
global RES_ID_SHADER_OILYTHING_I0 := 121
global RES_ID_SHADER_OVERSTIMULATEDNEURONS_I0 := 122
global RES_ID_SHADER_STARSHIP_I0 := 123
global RES_ID_SHADER_SUNSURFACE_I0 := 124
global RES_ID_SHADER_TOXICLAKE_I0 := 125
global RES_ID_SHADER_VORONOIBURNING_I0 := 126

global RES_ID_SHADER_VS := 1000
global RES_ID_SHADER_PS_2DCLOUDS := 1001
global RES_ID_SHADER_PS_4DLAVALAMP := 1002
global RES_ID_SHADER_PS_70SMELT := 1003
global RES_ID_SHADER_PS_ABSTRACTGLASSYFIELD := 1004
global RES_ID_SHADER_PS_ABSTRACTPAINTING := 1005
global RES_ID_SHADER_PS_ABSTRACTSHINE := 1006
global RES_ID_SHADER_PS_ABSTRACTVORTEX := 1007
global RES_ID_SHADER_PS_ACCRETION := 1008
global RES_ID_SHADER_PS_ALIENSKIN := 1009
global RES_ID_SHADER_PS_ALIENSPAWNINGPOOL := 1010
global RES_ID_SHADER_PS_ANOTHERWINDOWSTERMINALSHADER := 1011
global RES_ID_SHADER_PS_ASCEND := 1012
global RES_ID_SHADER_PS_BALATROBACKGROUND := 1013
global RES_ID_SHADER_PS_BALATROTWIST := 1014
global RES_ID_SHADER_PS_BASEWARPFBM := 1015
global RES_ID_SHADER_PS_BENTHORIZON := 1016
global RES_ID_SHADER_PS_BLACKHOLEACCRETIONDISK := 1017
global RES_ID_SHADER_PS_BLOODCELLS := 1018
global RES_ID_SHADER_PS_BLUEMOONOCEAN := 1019
global RES_ID_SHADER_PS_BLURRYCIRCLES := 1020
global RES_ID_SHADER_PS_BMTESTING04 := 1021
global RES_ID_SHADER_PS_BMTEST2 := 1022
global RES_ID_SHADER_PS_BOKEHEXPE03 := 1023
global RES_ID_SHADER_PS_BOKEHGRADIENT := 1024
global RES_ID_SHADER_PS_BOKEHLIGHTS := 1025
global RES_ID_SHADER_PS_BOKEHPARALLAX := 1026
global RES_ID_SHADER_PS_BRAINFALL := 1027
global RES_ID_SHADER_PS_CHEAPOCEAN := 1028
global RES_ID_SHADER_PS_CHILLSMOKEORB := 1029
global RES_ID_SHADER_PS_CLEARLYABUG := 1030
global RES_ID_SHADER_PS_COLORFADEPATTERN := 1031
global RES_ID_SHADER_PS_COLORFOG := 1032
global RES_ID_SHADER_PS_COLORFULFBMDOMAINWARPING := 1033
global RES_ID_SHADER_PS_COSMICFBMNOISE := 1034
global RES_ID_SHADER_PS_CRUMPLEDWAVE := 1035
global RES_ID_SHADER_PS_CUBEWAVE3 := 1036
global RES_ID_SHADER_PS_DAMASKROSE := 1037
global RES_ID_SHADER_PS_DETERIORATION := 1038
global RES_ID_SHADER_PS_DIGITALBRAIN := 1039
global RES_ID_SHADER_PS_DIGITALRAIN := 1040
global RES_ID_SHADER_PS_DISCOINFERNO := 1041
global RES_ID_SHADER_PS_DOMAINWARPEDFBMNOISE := 1042
global RES_ID_SHADER_PS_DOMAINWARPINGLEARN := 1043
global RES_ID_SHADER_PS_DOMAINWARPINGOIL := 1044
global RES_ID_SHADER_PS_DOMAINWARPINGTEST := 1045
global RES_ID_SHADER_PS_DRAWCIRCLE := 1046
global RES_ID_SHADER_PS_DRIFTINGWAVES := 1047
global RES_ID_SHADER_PS_DUNESANDWORM := 1048
global RES_ID_SHADER_PS_ENTERTHEMATRIX := 1049
global RES_ID_SHADER_PS_EXITTHEMATRIX := 1050
global RES_ID_SHADER_PS_EXPLOSIVETURBULENTNOISE := 1051
global RES_ID_SHADER_PS_FAKINGGOLDANDMURDER := 1052
global RES_ID_SHADER_PS_FATEBECKONS := 1053
global RES_ID_SHADER_PS_FBMDOMAINWARPING := 1054
global RES_ID_SHADER_PS_FBMNOISE := 1055
global RES_ID_SHADER_PS_FIRE := 1056
global RES_ID_SHADER_PS_FIREANDWATER := 1057
global RES_ID_SHADER_PS_FLOWEROFFRACTAL := 1058
global RES_ID_SHADER_PS_FORKTHEDRIVE := 1059
global RES_ID_SHADER_PS_FRACTALGALAXYPARALLAX := 1060
global RES_ID_SHADER_PS_GALVANIZETUNNEL := 1061
global RES_ID_SHADER_PS_GARGANTUARENDER := 1062
global RES_ID_SHADER_PS_GLASSWALL := 1063
global RES_ID_SHADER_PS_GLASSYWITHODDROTATION := 1064
global RES_ID_SHADER_PS_GLITTERY := 1065
global RES_ID_SHADER_PS_GLOWINGMARBLINGBLACK := 1066
global RES_ID_SHADER_PS_GOLDAGATE := 1067
global RES_ID_SHADER_PS_GREYLIQUID := 1068
global RES_ID_SHADER_PS_HAPPYLITTLEWINDOWSTERMINAL := 1069
global RES_ID_SHADER_PS_HOLOGRAPHICLIQUID := 1070
global RES_ID_SHADER_PS_HORIZONZERODAWNCLOUDS2D := 1071
global RES_ID_SHADER_PS_INSPACE := 1072
global RES_ID_SHADER_PS_INSIDETHEMATRIX := 1073
global RES_ID_SHADER_PS_INTERSTELLAR := 1074
global RES_ID_SHADER_PS_ISITSTILLRAYMARCHING := 1075
global RES_ID_SHADER_PS_ISOSCREENSAVER := 1076
global RES_ID_SHADER_PS_ITERATINGCAUSTICS := 1077
global RES_ID_SHADER_PS_JASZUNIVERSE := 1078
global RES_ID_SHADER_PS_KALEIDOSCOPECRYSTAL := 1079
global RES_ID_SHADER_PS_KALEIDOSCOPETUNNEL := 1080
global RES_ID_SHADER_PS_LAZERBEAMZ := 1081
global RES_ID_SHADER_PS_LIMESTONECAVE := 1082
global RES_ID_SHADER_PS_LINESYNAPSE := 1083
global RES_ID_SHADER_PS_LIQUIDWARP := 1084
global RES_ID_SHADER_PS_METALVORTEX := 1085
global RES_ID_SHADER_PS_MONSTER := 1086
global RES_ID_SHADER_PS_NANOSECONDSAFTERBIGBANG := 1087
global RES_ID_SHADER_PS_NEBULAFLIGHT := 1088
global RES_ID_SHADER_PS_NEBULASMOKE := 1089
global RES_ID_SHADER_PS_NEONPLASMASTORM := 1090
global RES_ID_SHADER_PS_NOISEACCIDENT := 1091
global RES_ID_SHADER_PS_NOISEANIMATIONELECTRIC := 1092
global RES_ID_SHADER_PS_NOISEANIMATIONFLOW := 1093
global RES_ID_SHADER_PS_NOISECRISTAL := 1094
global RES_ID_SHADER_PS_NOISEOIL := 1095
global RES_ID_SHADER_PS_NOX := 1096
global RES_ID_SHADER_PS_OVORTEX := 1097
global RES_ID_SHADER_PS_OILYTHING := 1098
global RES_ID_SHADER_PS_OPTICALSPAGHETTI := 1099
global RES_ID_SHADER_PS_ORGANICTEXTURE := 1100
global RES_ID_SHADER_PS_OVERSTIMULATEDNEURONS := 1101
global RES_ID_SHADER_PS_PAINT1 := 1102
global RES_ID_SHADER_PS_PAINTARCHIPELAGO := 1103
global RES_ID_SHADER_PS_PALACEOFMIND := 1104
global RES_ID_SHADER_PS_PATHTOTHECOLORFULINFINITY := 1105
global RES_ID_SHADER_PS_PERHAPSASCREENSAVER := 1106
global RES_ID_SHADER_PS_PINWHEELTRIANGLESSCREENSAVER := 1107
global RES_ID_SHADER_PS_PLAYINGWITHFBM := 1108
global RES_ID_SHADER_PS_POWERCHAINSAWMAN := 1109
global RES_ID_SHADER_PS_PRETTYCOLORS := 1110
global RES_ID_SHADER_PS_PRETTYHIP := 1111
global RES_ID_SHADER_PS_PROCESSINGDATA := 1112
global RES_ID_SHADER_PS_PROTEANCLOUDS := 1113
global RES_ID_SHADER_PS_RAINBOWSCREENSAVERANIMATION := 1114
global RES_ID_SHADER_PS_RAINDROPSGLASS := 1115
global RES_ID_SHADER_PS_RAYMARCHINGWAVES := 1116
global RES_ID_SHADER_PS_REFLECTIVETRUCHET := 1117
global RES_ID_SHADER_PS_RETROSCREENSAVERLINES := 1118
global RES_ID_SHADER_PS_ROCAILLE := 1119
global RES_ID_SHADER_PS_ROTATINGTORUS := 1120
global RES_ID_SHADER_PS_SATINLIKE := 1121
global RES_ID_SHADER_PS_SATORI := 1122
global RES_ID_SHADER_PS_SCREENSAVERWARPEDGRADWAVES := 1123
global RES_ID_SHADER_PS_SEAADVENTURE := 1124
global RES_ID_SHADER_PS_SHADETOBER29INJURED := 1125
global RES_ID_SHADER_PS_SIMPLESCREENSAVER := 1126
global RES_ID_SHADER_PS_SIMPLEX3DFBM := 1127
global RES_ID_SHADER_PS_SINGULARITY := 1128
global RES_ID_SHADER_PS_SMOKEFLYTHROUGH := 1129
global RES_ID_SHADER_PS_SOFTWHISPER := 1130
global RES_ID_SHADER_PS_SPACEEYE2 := 1131
global RES_ID_SHADER_PS_SPARKSFROMFIRE := 1132
global RES_ID_SHADER_PS_SPIRALSFORWINDOWSTERMINAL := 1133
global RES_ID_SHADER_PS_STARNEW := 1134
global RES_ID_SHADER_PS_STARSHINE := 1135
global RES_ID_SHADER_PS_STARFIELDSIMV2 := 1136
global RES_ID_SHADER_PS_STARFIELDWITHFBM := 1137
global RES_ID_SHADER_PS_STARLEIDOSCOPE := 1138
global RES_ID_SHADER_PS_STARSHIP := 1139
global RES_ID_SHADER_PS_SUNSURFACE := 1140
global RES_ID_SHADER_PS_TENTACLESOFLIGHT := 1141
global RES_ID_SHADER_PS_TILEABLEWATERCAUSTIC := 1142
global RES_ID_SHADER_PS_TILESINTERESTINGPATTERNS := 1143
global RES_ID_SHADER_PS_TOXICLAKE := 1144
global RES_ID_SHADER_PS_TRIANGLENOISE := 1145
global RES_ID_SHADER_PS_TURBULENCETEXTURE := 1146
global RES_ID_SHADER_PS_ULTRALIQUIDBOKEH := 1147
global RES_ID_SHADER_PS_UNDERWATERCAUSTICS := 1148
global RES_ID_SHADER_PS_VISTAESQUEWALLPAPER := 1149
global RES_ID_SHADER_PS_VOLUMETRICFIRE := 1150
global RES_ID_SHADER_PS_VORONOIBURNING := 1151
global RES_ID_SHADER_PS_WARPEDLIQUIDMETAL := 1152
global RES_ID_SHADER_PS_WORLEYNOISEWATERS := 1153
global RES_ID_SHADER_PS_WORMCITY := 1154

Shader_ExtractTextures() {
    global RES_ID_SHADER_ABSTRACTGLASSYFIELD_I0, RES_ID_SHADER_ABSTRACTGLASSYFIELD_I1, RES_ID_SHADER_ALIENSPAWNINGPOOL_I0, RES_ID_SHADER_BLACKHOLEACCRETIONDISK_I0, RES_ID_SHADER_BMTEST2_I0, RES_ID_SHADER_DIGITALBRAIN_I0, RES_ID_SHADER_DIGITALRAIN_I0, RES_ID_SHADER_DIGITALRAIN_I1, RES_ID_SHADER_DOMAINWARPEDFBMNOISE_I0, RES_ID_SHADER_ENTERTHEMATRIX_I0, RES_ID_SHADER_GARGANTUARENDER_I0, RES_ID_SHADER_GARGANTUARENDER_I1, RES_ID_SHADER_HOLOGRAPHICLIQUID_I0, RES_ID_SHADER_INTERSTELLAR_I0, RES_ID_SHADER_LIQUIDWARP_I0, RES_ID_SHADER_NEBULAFLIGHT_I0, RES_ID_SHADER_NEBULAFLIGHT_I1, RES_ID_SHADER_NEONPLASMASTORM_I0, RES_ID_SHADER_NEONPLASMASTORM_I1, RES_ID_SHADER_NOISEANIMATIONELECTRIC_I0, RES_ID_SHADER_NOISEANIMATIONFLOW_I0, RES_ID_SHADER_OILYTHING_I0, RES_ID_SHADER_OVERSTIMULATEDNEURONS_I0, RES_ID_SHADER_STARSHIP_I0, RES_ID_SHADER_SUNSURFACE_I0, RES_ID_SHADER_TOXICLAKE_I0, RES_ID_SHADER_VORONOIBURNING_I0
    if (!A_IsCompiled)
        return  ; dev mode loads from src/shaders/ directly
    DirCreate(A_Temp "\shaders")
    ResourceExtractToTemp(RES_ID_SHADER_ABSTRACTGLASSYFIELD_I0, "abstract_glassy_field_i0.png", A_Temp "\shaders")
    ResourceExtractToTemp(RES_ID_SHADER_ABSTRACTGLASSYFIELD_I1, "abstract_glassy_field_i1.jpg", A_Temp "\shaders")
    ResourceExtractToTemp(RES_ID_SHADER_ALIENSPAWNINGPOOL_I0, "alien_spawning_pool_i0.png", A_Temp "\shaders")
    ResourceExtractToTemp(RES_ID_SHADER_BLACKHOLEACCRETIONDISK_I0, "black_hole_accretion_disk_i0.jpg", A_Temp "\shaders")
    ResourceExtractToTemp(RES_ID_SHADER_BMTEST2_I0, "bmtest2_i0.png", A_Temp "\shaders")
    ResourceExtractToTemp(RES_ID_SHADER_DIGITALBRAIN_I0, "digital_brain_i0.png", A_Temp "\shaders")
    ResourceExtractToTemp(RES_ID_SHADER_DIGITALRAIN_I0, "digital_rain_i0.png", A_Temp "\shaders")
    ResourceExtractToTemp(RES_ID_SHADER_DIGITALRAIN_I1, "digital_rain_i1.png", A_Temp "\shaders")
    ResourceExtractToTemp(RES_ID_SHADER_DOMAINWARPEDFBMNOISE_I0, "domain_warped_fbm_noise_i0.png", A_Temp "\shaders")
    ResourceExtractToTemp(RES_ID_SHADER_ENTERTHEMATRIX_I0, "enter_the_matrix_i0.png", A_Temp "\shaders")
    ResourceExtractToTemp(RES_ID_SHADER_GARGANTUARENDER_I0, "gargantua_render_i0.png", A_Temp "\shaders")
    ResourceExtractToTemp(RES_ID_SHADER_GARGANTUARENDER_I1, "gargantua_render_i1.jpg", A_Temp "\shaders")
    ResourceExtractToTemp(RES_ID_SHADER_HOLOGRAPHICLIQUID_I0, "holographic_liquid_i0.png", A_Temp "\shaders")
    ResourceExtractToTemp(RES_ID_SHADER_INTERSTELLAR_I0, "interstellar_i0.png", A_Temp "\shaders")
    ResourceExtractToTemp(RES_ID_SHADER_LIQUIDWARP_I0, "liquid_warp_i0.png", A_Temp "\shaders")
    ResourceExtractToTemp(RES_ID_SHADER_NEBULAFLIGHT_I0, "nebula_flight_i0.png", A_Temp "\shaders")
    ResourceExtractToTemp(RES_ID_SHADER_NEBULAFLIGHT_I1, "nebula_flight_i1.png", A_Temp "\shaders")
    ResourceExtractToTemp(RES_ID_SHADER_NEONPLASMASTORM_I0, "neon_plasma_storm_i0.png", A_Temp "\shaders")
    ResourceExtractToTemp(RES_ID_SHADER_NEONPLASMASTORM_I1, "neon_plasma_storm_i1.png", A_Temp "\shaders")
    ResourceExtractToTemp(RES_ID_SHADER_NOISEANIMATIONELECTRIC_I0, "noise_animation_electric_i0.png", A_Temp "\shaders")
    ResourceExtractToTemp(RES_ID_SHADER_NOISEANIMATIONFLOW_I0, "noise_animation_flow_i0.png", A_Temp "\shaders")
    ResourceExtractToTemp(RES_ID_SHADER_OILYTHING_I0, "oily_thing_i0.png", A_Temp "\shaders")
    ResourceExtractToTemp(RES_ID_SHADER_OVERSTIMULATEDNEURONS_I0, "overstimulated_neurons_i0.png", A_Temp "\shaders")
    ResourceExtractToTemp(RES_ID_SHADER_STARSHIP_I0, "starship_i0.png", A_Temp "\shaders")
    ResourceExtractToTemp(RES_ID_SHADER_SUNSURFACE_I0, "sun_surface_i0.png", A_Temp "\shaders")
    ResourceExtractToTemp(RES_ID_SHADER_TOXICLAKE_I0, "toxic_lake_i0.png", A_Temp "\shaders")
    ResourceExtractToTemp(RES_ID_SHADER_VORONOIBURNING_I0, "voronoi_burning_i0.png", A_Temp "\shaders")
}

; Get runtime path to a shader texture file.
; Compiled: extracted to %TEMP%\shaders\. Dev: loaded from src\shaders\ directly.
Shader_GetTexturePath(fileName) {
    if (A_IsCompiled)
        return A_Temp "\shaders\" fileName
    ; Dev mode: walk up from A_ScriptDir to find src/shaders/
    return A_ScriptDir "\shaders\" fileName
}
