# ============================================================
# Alt-Tabby Compile Script (PowerShell)
# ============================================================
# Compiles alt_tabby.ahk to release/AltTabby.exe
# Usage: compile.ps1 [--test-mode] [--timing] [--force]
#   --test-mode   Skip process killing and docs generation, suppress banners
#   --timing      Output machine-readable per-step timing (TIMING:step:ms)
#   --force       Force recompilation even if exe is up to date
# ============================================================

param(
    [Alias("test-mode")]
    [switch]$testMode,
    [switch]$timing,
    [switch]$force
)

# --- Timing Infrastructure ---
# Uses Stopwatch for millisecond precision (no batch %TIME% parsing needed)
$stepSw = [System.Diagnostics.Stopwatch]::new()

function Reset-StepTimer { $script:stepSw.Restart() }
function Record-Step {
    param([string]$Label)
    $script:stepSw.Stop()
    if ($script:timing) {
        Write-Output "TIMING:${Label}:$($script:stepSw.ElapsedMilliseconds)"
    }
}

# --- Locate tools ---
$ahk2exe = "C:\Program Files\AutoHotkey\Compiler\Ahk2Exe.exe"
$ahk2base = "C:\Program Files\AutoHotkey\v2\AutoHotkey64.exe"

if (-not (Test-Path $ahk2exe)) {
    Write-Output "ERROR: Ahk2Exe.exe not found at: $ahk2exe"
    Write-Output "Please install AutoHotkey with the compiler component."
    exit 1
}
if (-not (Test-Path $ahk2base)) {
    Write-Output "ERROR: AutoHotkey v2 not found at: $ahk2base"
    Write-Output "Please install AutoHotkey v2."
    exit 1
}

if (-not $testMode) {
    Write-Output ""
    Write-Output "============================================================"
    Write-Output "Alt-Tabby Compiler"
    Write-Output "============================================================"
    Write-Output ""
    Write-Output "Found compiler: $ahk2exe"
    Write-Output "Found v2 base:  $ahk2base"
    Write-Output ""
}

# --- Read version ---
$versionFile = Join-Path $PSScriptRoot "VERSION"
$version = Get-Content $versionFile -ErrorAction SilentlyContinue | Select-Object -First 1
if ($version) { $version = $version.Trim() }
if (-not $version) {
    Write-Output "ERROR: Could not read VERSION file"
    exit 1
}

if (-not $testMode) {
    Write-Output "Version: $version"
    Write-Output ""
}

# --- Generate config documentation (smart skip) ---
# In test mode: skip entirely (not needed for testing)
# In normal mode: skip if options.md is newer than both source files
# --force overrides the smart skip (but not test mode)
Reset-StepTimer
$docsLabel = "Docs"

if ($testMode) {
    $docsLabel = "Docs (skipped)"
} else {
    $docsNeeded = $true
    $docsFile = Join-Path $PSScriptRoot "docs\options.md"
    $configSrc = Join-Path $PSScriptRoot "src\shared\config_registry.ahk"
    $docsBuildScript = Join-Path $PSScriptRoot "build-config-docs.ahk"

    if (-not $force -and (Test-Path $docsFile)) {
        $docsTime = (Get-Item $docsFile).LastWriteTime
        $src1Time = (Get-Item $configSrc).LastWriteTime
        $src2Time = (Get-Item $docsBuildScript).LastWriteTime
        if ($docsTime -gt $src1Time -and $docsTime -gt $src2Time) {
            $docsNeeded = $false
            $docsLabel = "Docs (cached)"
        }
    }

    if (-not $docsNeeded) {
        Write-Output "Config documentation up to date - skipping generation"
        Write-Output ""
    } else {
        Write-Output "Generating config documentation..."
        $docsProc = Start-Process -FilePath $ahk2base -ArgumentList "/ErrorStdOut `"$docsBuildScript`"" -Wait -PassThru -WindowStyle Hidden
        if ($docsProc.ExitCode -ne 0) {
            Write-Output "ERROR: Failed to generate config documentation"
            exit 1
        }
        if (-not (Test-Path $docsFile)) {
            Write-Output "ERROR: docs\options.md was not created"
            exit 1
        }
        Write-Output "  - Generated docs\options.md"
        Write-Output ""
    }
}
Record-Step $docsLabel

# --- Generate version_info.ahk with Ahk2Exe directives ---
# Always regenerated (content depends on VERSION file, essentially free)
Reset-StepTimer
$versionInfoPath = Join-Path $PSScriptRoot "src\version_info.ahk"
$versionInfoLines = @(
    "; Auto-generated by compile.ps1 - DO NOT EDIT"
    "; Version read from VERSION file"
    ";@Ahk2Exe-SetProductVersion $version"
    ";@Ahk2Exe-SetFileVersion ${version}.0"
)
[IO.File]::WriteAllLines($versionInfoPath, $versionInfoLines)
Record-Step "Version Stamp"

# --- Setup paths ---
$releaseDir = Join-Path $PSScriptRoot "release"
$scriptDir = Join-Path $PSScriptRoot "src"
$inputFile = Join-Path $scriptDir "alt_tabby.ahk"
$outputFile = Join-Path $releaseDir "AltTabby.exe"
$iconFile = Join-Path $PSScriptRoot "resources\icon.ico"

if (-not (Test-Path $releaseDir)) {
    New-Item -ItemType Directory -Path $releaseDir -Force | Out-Null
}

if (-not (Test-Path $inputFile)) {
    Write-Output "ERROR: Source file not found: $inputFile"
    exit 1
}

if (-not $testMode) {
    Write-Output "Compiling: $inputFile"
    Write-Output "Output:    $outputFile"
    Write-Output "Base:      $ahk2base"
    Write-Output ""
}

# --- Smart exe skip: check if exe is newer than all source files ---
# Compares exe timestamp against: src\*.ahk (excluding version_info.ahk),
# VERSION file, and icon. Skips recompilation if exe is newer than all.
# version_info.ahk is excluded because we regenerate it every run; VERSION
# file changes are caught explicitly.
# Native PowerShell — no subprocess needed (~0ms vs ~300ms in batch)
$exeNeeded = $true
$exeLabel = "Ahk2Exe"

if (-not $force -and (Test-Path $outputFile)) {
    $exeTime = (Get-Item $outputFile).LastWriteTime
    $srcFiles = @(Get-ChildItem -Path $scriptDir -Filter "*.ahk" -Recurse |
                  Where-Object { $_.Name -ne "version_info.ahk" })
    $checkItems = $srcFiles + @(Get-Item $versionFile)
    if (Test-Path $iconFile) {
        $checkItems += Get-Item $iconFile
    }
    $newest = $checkItems | Sort-Object LastWriteTime -Descending | Select-Object -First 1
    if ($exeTime -gt $newest.LastWriteTime) {
        $exeNeeded = $false
        $exeLabel = "Ahk2Exe (cached)"
    }
}

if (-not $exeNeeded -and -not $testMode) {
    Write-Output "Compilation skipped - exe is newer than source"
    Write-Output "      Use --force to override"
    Write-Output ""
}

# --- Kill any running AltTabby processes ---
# Skipped when: test mode (test runner handles it) OR exe cached (nothing to write)
if ($exeNeeded -and -not $testMode) {
    Reset-StepTimer
    Write-Output "Checking for running AltTabby processes..."
    $running = Get-Process -Name "AltTabby" -ErrorAction SilentlyContinue
    if ($running) {
        Write-Output "Found running AltTabby.exe - attempting to terminate..."
        try {
            Stop-Process -Name "AltTabby" -Force -ErrorAction Stop
            Write-Output "  - Terminated AltTabby.exe"
            Start-Sleep -Seconds 2
        } catch {
            Write-Output "WARNING: Could not terminate AltTabby.exe"
            Write-Output "         Process may be running as Administrator."
            Write-Output "         Please close it manually and try again."
            Write-Output ""
            exit 1
        }
    } else {
        Write-Output "  - No running AltTabby.exe found"
    }
    Write-Output ""
    Record-Step "Process Check"
}

# --- Compile using v2 base interpreter ---
Reset-StepTimer
$compileError = 0

if ($exeNeeded) {
    $compileArgs = "/in `"$inputFile`" /out `"$outputFile`" /base `"$ahk2base`""
    if (Test-Path $iconFile) {
        $compileArgs += " /icon `"$iconFile`""
    }
    $compileArgs += " /silent verbose"

    $compileProc = Start-Process -FilePath $ahk2exe -ArgumentList $compileArgs -Wait -PassThru -WindowStyle Hidden
    $compileError = $compileProc.ExitCode
}
Record-Step $exeLabel

if ($compileError -ne 0) {
    Write-Output ""
    Write-Output "ERROR: Compilation failed with error code $compileError"
    Write-Output ""
    if (-not $testMode) {
        Write-Output "Try running Ahk2Exe.exe GUI and selecting:"
        Write-Output "  Source: $inputFile"
        Write-Output "  Base File: v2.0.19 U64 AutoHotkey64.exe"
        Write-Output ""
    }
    exit 1
}

# --- Verify output exists ---
Reset-StepTimer
if (-not (Test-Path $outputFile)) {
    Write-Output ""
    Write-Output "ERROR: Output file not created!"
    Write-Output "Expected: $outputFile"
    Write-Output ""
    if (-not $testMode) {
        Write-Output "The compilation may have failed silently. Try:"
        Write-Output "  1. Run Ahk2Exe.exe GUI manually"
        Write-Output "  2. Select Source: $inputFile"
        Write-Output "  3. Select Base File: v2.0.19 U64 AutoHotkey64.exe"
        Write-Output ""
    }
    exit 1
}
Record-Step "Verify"

# --- Success ---
if (-not $testMode) {
    Write-Output ""
    Write-Output "============================================================"
    Write-Output "SUCCESS - Compiled to: $outputFile"
    Write-Output "============================================================"
    Write-Output ""
    Write-Output "Usage:"
    Write-Output "  AltTabby.exe             - Launch GUI + Store"
    Write-Output "  AltTabby.exe --store     - Store server only"
    Write-Output "  AltTabby.exe --viewer    - Debug viewer only"
    Write-Output "  AltTabby.exe --gui-only  - GUI only (store must be running)"
    Write-Output ""
    Write-Output "TIP: Run as Administrator for full functionality"
    Write-Output "     (required to intercept Alt+Tab in admin windows)"
    Write-Output ""
}

exit 0
